---   
- name: debug
  debug:
    msg: "{{ acc_new_pw }}"
  when: var_debug == 69 

- name: block
  block:
  - name: "'VMware vCenter' type only: update password for {{ var_AAP_Credentials }}({{ item }})"
    when: item == 'VMware vCenter'
    ansible.controller.credential:
      name: "{{ var_AAP_Credentials }}"
      description: Machine credential that leverages kerberos
      organization: "{{ var_AAP_organization }}"
      credential_type: "{{ item }}"
      state: present
      inputs:
        username: "{{ var_LDAPUsername }}"
        password: "{{ acc_new_pw }}"
        host: "{{ var_AAP_VCenter_Host }}"
    #run_once: true
    no_log: true
    delegate_to: localhost

- name: block
  block:
  - name: "All other type: update password for {{ var_AAP_Credentials }}({{ item }})"
    when: item != 'VMware vCenter'
    ansible.controller.credential:
      name: "{{ var_AAP_Credentials }}"
      description: "credential created by playbook"
      organization: "{{ var_AAP_organization }}"
      credential_type: "{{ item }}"
      state: present
      inputs:
        username: "{{ var_LDAPUsername }}"
        password: "{{ acc_new_pw }}"
    no_log: true
    delegate_to: localhost