---
- name: debug
  debug:
    msg: "{{ acc_new_pw }}"
  when: var_debug == 69 

- name: "update password for '{{ var_sAMAccountName }}' - '{{ var_LDAPUsername }}' in ADDS"
  microsoft.ad.user:
    domain_server: "{{ var_domain_server }}"      
    domain_username: "{{ ansible_user }}"
    domain_password: "{{ ansible_password }}"   
    identity: "{{ var_sAMAccountName }}"
    name: "{{ var_sAMAccountName }}"
    password: "{{  acc_new_pw }}"
    state: present
    path: "{{ var_LDAPBaseDN }}"
    update_password: when_changed
