---
- name: stig-ansible-hardening ( Windows 2022, RHEL 8 and vCenter 8)
  hosts: all
  gather_facts: false
  vars:
    
  tasks:   
  - name: import role
    include_role:
      name: win2022STIG  

