---
- name: Playbook to upgrade N9kv 
  hosts: "{{ _groups }}"
  gather_facts: True
  
  tasks:

  - name: Set current N9kv version as variable
    ansible.builtin.set_fact:
      current_nxos_ver: "{{ ansible_facts['net_image'] | split ('nxos.') | last | trim | split ('.bin') | first | trim }}"

  - name: Verify new_image
    ansible.builtin.set_fact:
      verify_image: "{{ new_image | split ('nxos.') | last | trim | split ('.bin') | first | trim }}"
  - debug:
      msg: "New Image to upgrade {{ verify_image }}"

  - name: Check if correct image still exist in bootflash, if not FAIL the playbook
    cisco.nxos.nxos_command:
      commands: 'dir bootflash: | include {{ new_image }}'
    register: check_image
    failed_when: check_image.stdout[0].find( new_image )  == -1

  - name: Check if the switch was already upgraded
    ansible.builtin.debug:
      msg: 
      - "Current Version: {{ current_nxos_ver }}"
      - "Desired Version: {{ verify_image }}"

  - name: Install/Upgrade NXOS Software
    check_mode: false
    cisco.nxos.nxos_install_os:
      system_image_file: '{{ new_image }}'
      issu: no
    register: install_output
    vars:
      ansible_command_timeout: 600
      ansible_connect_timeout: 600
    when: current_nxos_ver != verify_image
   
  - debug:
      var: install_output
    when: current_nxos_ver != verify_image

  - name: Waiting for reboot
    ansible.builtin.wait_for_connection:
      delay: 60
      timeout: 600
    when: current_nxos_ver != verify_image

  - name: Reset ssh connection 
    ansible.builtin.meta: reset_connection

  - name: Check post upgrade version
    cisco.ios.ios_facts:

  - name: Assert that switch is running with the target NXOS version {{ verify_image }} After Upgrade
    assert:
        quiet: no
        success_msg: "{{ inventory_hostname }} has been upgraded to {{ verify_image }}"
        fail_msg: "Failed to upgrade the {{ inventory_hostname }}, it is still runninng {{ current_nxos_ver }}"
        that:
          - "ansible_facts['net_image'] | split ('nxos.') | last | trim | split ('.bin') | first | trim == verify_image"
          # - "'{{ ansible_facts['net_image'] | split ('nxos.') | last | trim | split ('.bin') | first | trim }}' == '{{ verify_image }}'"