#cloud-config
users:
- default
- name: sshuser
  shell: /bin/bash
  groups: wheel
  sudo:
  - ALL=(ALL) NOPASSWD:ALL
  lock_passwd: true
  ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKj0gkXP0BcQStTMfHOBBfF/7ZurbR0S1dpIYngR5WG/
    centos sshuser key
