
- name: "get snapshot with name including string='{{ snapshot_name_filter }}' for all VMs in datacenter={{item}}"
  community.vmware.vmware_all_snapshots_info:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    datacenter: '{{ item }}'
    match_type: "includes"
    filters:
      #vm_name: "{{ guest_name }}"
      name: "{{ snapshot_name_filter }}"
      #description: "{{ snapshot_desc_filter }}"
  delegate_to: localhost
  register: snapshot_info

- set_fact:
    #var_snapshotcount: "{{ item }} has {{ snapshot_info.vmware_all_snapshots_info| length }} snapshot"
    var_snapshotcount: "{{ snapshot_info.vmware_all_snapshots_info| length }}"

- debug:
    var: "{{ item }} has {{ var_snapshotcount }} snapshot"

- name: remove snapshot
  block:
    - name: removing snapshot that age > {{var_snapshotage}} days old
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{item}}"
        folder: "{{local_item.folder}}"
        name: "{{ local_item.vm_name }}"
        state: absent
        snapshot_id: "{{ local_item.id }}"
      when:
        - (now('%Y-%m-%d') - local_item.creation_time.split('T').0| to_datetime('%Y-%m-%d')).days |int > var_snapshotage
        - not 'Snapshot used by Content Library' in local_item.description    
      with_items: 
        - "{{ snapshot_info.vmware_all_snapshots_info }}"
      loop_control:
        loop_var: local_item
      delegate_to: localhost
  when: var_snapshotcount|int > 0