---
- name: Move archive log files off to the share location
  hosts: all
  gather_facts: no
   
  tasks:
    - name: Execute Move-files function
      ansible.windows.win_shell: |
        Function Move-files {
            [CmdletBinding()]
            Param(
                [Parameter(Mandatory=$true)]
                [string] $Path,     
                [Parameter(Mandatory=$true)]
                [string] $TargetPath,
                [Parameter(Mandatory=$false)]
                [string] $FilterOn = '*',
                [Parameter(Mandatory=$false)]
                [string] $Days = '0'
            )
            Begin{
                $dateTime = (Get-Date).AddDays([int]$Days)
                $computerName = $env:COMPUTERNAME
                $serverTargetPath = Join-Path -Path $TargetPath -ChildPath $computerName
            }
            Process{
                Try {
                    if ( !(Test-Path -PathType container $serverTargetPath) ){
                        New-Item -ItemType Directory -Path $serverTargetPath | Out-Null
                    }
                    
                    $movedFiles = Get-ChildItem -Path $Path -Recurse -File -Filter $FilterOn | 
                        Where-Object { $_.LastWriteTime -lt $dateTime } | 
                        ForEach-Object {
                            Move-Item -Path $_.FullName -Destination "$serverTargetPath" -Force -PassThru
                            $_.Name
                        }
                    
                    $fileCount = ($movedFiles | Measure-Object).Count
                    Write-Output "Moved $fileCount files FROM: $($serverTargetPath)\$($FilterOn) TO: $serverTargetPath"
                }
                Catch{ 
                    Write-Error $_.Exception.Message
                    throw
                }
            }
        }
        
        Move-files -Path "{{ source_path }}" -TargetPath "{{ target_path }}" -FilterOn "{{ file_filter }}" -Days "{{ days_old }}"
      register: move_result

    - name: Display results
      debug:
        var: move_result.stdout_lines
