---
- name: Provision VM snapshot
  hosts: all #localhost
#  connection: local
  gather_facts: false
  vars:
    vcenter_username: "{{AnsvCenterAdmin_username}}"
    vcenter_password: "{{AnsvCenterAdmin_password}}"
  roles:
    - vm_snapshot
  