---
- name: playbook to run powershell script remotely
  hosts: all
  become_method: runas
  gather_facts: yes
  connection: winrm
  port: 5986

  vars:
    var_ps_folder:        'ps_scripts'                       # root folder under files/
    var_ps_script_file:   'cvs_orphaned_vmdks.ps1'
    var_parameter_action: 'get_orphaned_zombie_vmdks'

    var_vCenterList:      'esoco26vcs01.washdc.state.sbu, esocoewvcs.washdc.state.sbu, esocoewvcs01.washdc.state.sbu, esocoewvcs02.washdc.state.sbu, esoco26vcs02.washdc.state.sbu'   # <-- your vCenters, comma-separated

    var_eMailReport:      'yes'                              # 'yes' to actually send
    var_SMTPServer:       'dom1.dom2.dom3.example'        # <-- your relay
    var_MailToString:     'user3@dom3.example'
    var_MailCcString:     ''
    var_MailSubjectstring: 'Ansible-Report: VMware Unattached Disk Review'

    var_MinimumDiskGB:    '1'                                # skip tiny descriptor/noise files below this size
    var_DatastoreNameRegex: '.*'                             # optional datastore name filter

  tasks:
  - name: "Create temporary directory"
    ansible.windows.win_tempfile:
      state: directory
    register: tempdir

  - name: "Script Operations"
    block:
    - name: "Copy Scripts to Host"
      ansible.windows.win_copy:
        src: "files/{{ var_ps_folder }}"
        dest: "{{ tempdir.path }}"

    - name: check if file exist
      ansible.windows.win_stat:
        path: '{{ tempdir.path }}\{{ var_ps_folder }}\{{ var_ps_script_file }}'
      register: file_data

    - name: Run PowerShell script
      when: file_data.stat.exists == true
      no_log: false
      environment:
        VC_USER: "{{ vcenter_username }}"
        VC_PASS: "{{ vcenter_password }}"
      ansible.windows.win_command: >
        powershell.exe -ExecutionPolicy ByPass
        -File "{{ tempdir.path }}\{{ var_ps_folder }}\{{ var_ps_script_file }}"
        -Action "{{ var_parameter_action }}" -eMailReport "{{ var_eMailReport }}"
        -SMTPServer "{{ var_SMTPServer }}"
        -MailToString "{{ var_MailToString }}"
        -MailCcString "{{ var_MailCcString }}"
        -MailSubjectstring "{{ var_MailSubjectstring }}"
        -vCenterList "{{ var_vCenterList }}"
        -MinimumDiskGB "{{ var_MinimumDiskGB }}"
        -DatastoreNameRegex "{{ var_DatastoreNameRegex }}"

    - name: "List the debug folder content"
      ansible.windows.win_shell: 'ls -Recurse {{ tempdir.path }}\{{ var_ps_folder }}'

    always:
    - name: "Cleanup Temporary Files"
      ansible.windows.win_file:
        state: absent
        path: "{{ tempdir.path }}"
