/**
 * Action: buildHtmlReport
 * Module: com.corp.serverreboot
 *
 * Render the run results into an HTML summary table (mirrors the old
 * Ansible email body). Pure function - no side effects.
 *
 * @param {Array/Properties} results - each: { adName, fqdn, matchedVmName,
 *                                    status, reason, message, timestamp, elapsedSec }
 * @param {string} headerNote        - free-text note (old var_HeaderNotesSubstr)
 * @returns {string} HTML document
 */

results = results || [];

function esc(s) {
    return String(s == null ? "" : s)
        .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
function color(status) {
    if (status === "SUCCESS") { return "#1e7e34"; }
    if (status === "FAILED") { return "#c0392b"; }
    return "#b8860b"; // SKIPPED
}

var counts = { SUCCESS: 0, FAILED: 0, SKIPPED: 0 };
for (var i = 0; i < results.length; i++) {
    var s = results[i].status || "SKIPPED";
    counts[s] = (counts[s] || 0) + 1;
}

var rows = "";
for (var j = 0; j < results.length; j++) {
    var r = results[j];
    rows +=
        '<tr>' +
        '<td style="padding:6px 10px;border:1px solid #ddd;">' + esc(r.adName) + '</td>' +
        '<td style="padding:6px 10px;border:1px solid #ddd;">' + esc(r.matchedVmName || "-") + '</td>' +
        '<td style="padding:6px 10px;border:1px solid #ddd;font-weight:bold;color:' +
            color(r.status) + ';">' + esc(r.status) + '</td>' +
        '<td style="padding:6px 10px;border:1px solid #ddd;">' + esc(r.reason) + '</td>' +
        '<td style="padding:6px 10px;border:1px solid #ddd;">' + esc(r.message) + '</td>' +
        '<td style="padding:6px 10px;border:1px solid #ddd;">' + esc(r.timestamp) + '</td>' +
        '</tr>';
}

var html =
    '<html><body style="font-family:Segoe UI,Arial,sans-serif;font-size:13px;color:#222;">' +
    '<h2 style="margin-bottom:4px;">Server Reboot Report</h2>' +
    (headerNote ? '<p style="margin-top:0;color:#555;">' + esc(headerNote) + '</p>' : '') +
    '<p><b>Total:</b> ' + results.length +
    ' &nbsp; <b style="color:#1e7e34;">Success:</b> ' + counts.SUCCESS +
    ' &nbsp; <b style="color:#c0392b;">Failed:</b> ' + counts.FAILED +
    ' &nbsp; <b style="color:#b8860b;">Skipped:</b> ' + counts.SKIPPED + '</p>' +
    '<table style="border-collapse:collapse;border:1px solid #ddd;">' +
    '<thead><tr style="background:#f4f4f4;">' +
    '<th style="padding:6px 10px;border:1px solid #ddd;text-align:left;">AD Name</th>' +
    '<th style="padding:6px 10px;border:1px solid #ddd;text-align:left;">Matched VM</th>' +
    '<th style="padding:6px 10px;border:1px solid #ddd;text-align:left;">Status</th>' +
    '<th style="padding:6px 10px;border:1px solid #ddd;text-align:left;">Reason</th>' +
    '<th style="padding:6px 10px;border:1px solid #ddd;text-align:left;">Detail</th>' +
    '<th style="padding:6px 10px;border:1px solid #ddd;text-align:left;">Timestamp (UTC)</th>' +
    '</tr></thead><tbody>' + rows + '</tbody></table>' +
    '<p style="color:#888;margin-top:16px;">Generated by VCF Orchestrator - Server Reboot Automation.</p>' +
    '</body></html>';

return html;
