---
- name: dynamic inventory of ESXi Hosts for each Cluster
  hosts: localhost
  collections:
  - community.vmware
  vars:
    # vcenter_hostname: "vc.corp.local"
    # var_datacenter_name: 'VxRail-Datacenter'
    # var_cluster_name:
    #     - 'VxRail-Virtual-SAN-Cluster-2f4158d4-ab51-4b26-8d2f-239810aecf13'
    #     - 'VxRail-Virtual-SAN-Cluster-2f4158d4-ab51-4b26-8d2f-239810aecf13'
    # var_test_port:
    #     - 22
    #     - 443
    #     - 80

  tasks:
  - name: Gather info about the cluster 
    include_tasks: tasks/get_esxi_inventory.yml
    with_items: "{{ var_cluster_name }}"

  # - name: debug
  #   debug:
  #     msg: "{{ cluster_hosts }}"