---
- name: playbook to run powershell script remotely
  hosts: all
  become_method: runas
  gather_facts: no
  connection: winrm
  port: 5986

  vars:
    # var_ps_folder: 'thieu_scripts' # root folder of scripts

  tasks:
  - name: "Create temporary directory"
    ansible.windows.win_tempfile:
      state: directory
    register: tempdir

  - name: "Scipt Operations"
    block:
    - name: "Copy Scripts to Host"
      ansible.windows.win_copy:
        src: "files/{{var_ps_folder}}"
        dest: "{{ tempdir.path }}"

    - name: check if file exist
      ansible.windows.win_stat:
        path: "{{ tempdir.path }}\\{{var_ps_folder}}\\{{var_ps_script_file}}"
      register: file_data

    - name: Run PowerShell script
      when: file_data.stat.exists == true
      ansible.windows.win_command: powershell.exe -ExecutionPolicy ByPass
        -File "{{ tempdir.path }}\\{{var_ps_folder}}\\{{var_ps_script_file}}"
        -Action "{{var_parameter_action}}"
        -ADGroupMember "{{var_ADGroupMember}}"
        -FolderTarget "{{var_FolderTarget}}"
        -FolderIncluded "{{var_FolderIncluded}}"
        -ForceEnable "{{var_ForceEnable}}"
        -NumberOfDays "{{var_NumberOfDays}}"
        -FilterOn "{{var_FilterOn}}"
        -DomainName "{{var_DomainName}}"

    always:
    - name: "Cleanup Temporary Files"
      ansible.windows.win_file:
        state: absent
        path: "{{ tempdir.path }}"
