---
- name: Playbook to stage/scp to Cat9kv bootflash
  hosts: "{{ _groups }}"
  gather_facts: False
  vars:
   ansible_network_cli_ssh_type: paramiko

  tasks:

  - name: Check if image already exist in bootflash
    cisco.ios.ios_command:
      commands: 'dir bootflash: | include {{ new_image }}'
    register: check_image

  - name: Enable scp
    cisco.ios.ios_config:
      lines: 
      - ip scp server enable
      - ip ssh window-size 131072 
      - ip tcp window-size 131072
    when:
      check_image.stdout[0].find( new_image )  == -1
 
  - name: Retreive Image from backup-server to execution environment
    ansible.builtin.fetch:
      src: "~/upgrades/{{ new_image }}"
      dest: "{{ playbook_dir }}"
    delegate_to: backup-server
    run_once: true
    when:
     check_image.stdout[0].find( new_image )  == -1
    vars:
      ansible_user: '{{ upgrade_username }}'
      ansible_password: '{{ upgrade_password }}'

  - name: Copy config file to router
    ansible.netcommon.net_put:
      src: /runner/project/{{play_dir}}{{ inventory_hostname }}{{upgrade_dir}}{{ new_image }}
      dest: "{{ new_image }}"
      remote_user: admin  
    when: 
     - check_image.stdout[0].find( new_image )  == -1
  
  - name: Verify SHA512 Hash of Image File
    vars:
     ansible_command_timeout: 1200
    cisco.ios.ios_command:
      commands: 'verify /sha512 bootflash:/{{ new_image }} {{ sha_hash }}'
    register: sha_hash_verification_results
  
  - name: Set SHA512_hash_verification to pass
    ansible.builtin.set_fact:
     sha_hash_verification: "pass"
    when: sha_hash_verification_results.stdout[0].find('Verified') != -1

  - name: Fail Task if SHA512 Hash Check Fails
    fail:
      msg: "SHA512 Hash Check Fails. Please check the uploaded image!"
    when: sha_hash_verification_results.stdout[0].find('Verified') == -1
