---
- name: Add CVS service account to local Administrators
  hosts: all
  gather_facts: no
  connection: winrm
  port: 5986

  vars:
    var_admin_member: "CONNECT\\svc-CVSAnsWin"

  tasks:
    - name: Add service account to local Administrators
      ansible.windows.win_group_membership:
        name: Administrators
        members:
          - "{{ var_admin_member }}"
        state: present