
# R-257816 RHEL-09-213105
rhel9STIG_stigrule_257816_Manage: True
rhel9STIG_stigrule_257816_user_max_user_namespaces_Value: 63556
rhel9STIG_stigrule_257816_user_max_user_namespaces_File: /etc/sysctl.d/99-sysctl.conf

# R-257816 RHEL-09-213105
rhel9STIG_stigrule_257816_v1_Manage: True
rhel9STIG_stigrule_257816_v1_user_max_user_namespaces_Value: 63556
rhel9STIG_stigrule_257816_v1_user_max_user_namespaces_File: /etc/sysctl.conf

# R-257835 RHEL-09-215060 # removed, installed
rhel9STIG_stigrule_257835_Manage: True
rhel9STIG_stigrule_257835_tftp_State: removed

# R-257984 RHEL-09-255040 # no, yes
rhel9STIG_stigrule_257984_Manage: True
rhel9STIG_stigrule_257984_PermitEmptyPasswords_Line: PermitEmptyPasswords no

# R-258113 RHEL-09-611120
rhel9STIG_stigrule_258113_Manage: True
rhel9STIG_stigrule_258113__etc_security_pwquality_conf_Line: 'maxclassrepeat = 9'

# CVS 
cvs_sudoers_nopasswd_Manage: True
cvs_sudoers_nopasswd_conf_Line: 'ansiblelocal        ALL=(ALL)       NOPASSWD: ALL'
