---
- name: playbook to run powershell script remotely
  hosts: all
  become_method: runas
  gather_facts: yes
  connection: winrm
  port: 5986

  vars:
    # var_ps_folder: 'thieu_scripts' # root folder of scripts
    # var_ps_script_file: 'ESOC-Admin-Scripts.ps1' # script to be execute
    # var_parameter_action: 'Get-ServiceAccountExpiration' # parameter -Action
    # var_eMailReport: 'yes' # parameter email configuration
    # var_SMTPServer: 'nccsmtprelay.irm.state.gov' # parameter email configuration
    # var_MailToString: "NguyenTD4@state.gov,NguyenTD4@state.gov" # parameter email configuration 
    # var_MailCcString: "NguyenTD4@state.gov,NguyenTD4@state.gov" # parameter email configuration
    # var_MailSubjectstring: 'Ansible-Report: ESOC Service Account Expiration Report' # parameter email configuration
    # var_OUPath: 'OU=Service Accounts,OU=ESOC,OU=M,OU=IRM,DC=washdc,DC=state,DC=sbu' # parameter OU path to the services location
    # var_cleanup_temporary_folder: true # parameter clean your crap after done
    # var_ADGroupMember: 'ESOC-Monitoring-Servers' # parameter security group of list of servers
    # var_HeaderNotesSubstr: "ESOC-Monitoring-Servers" # parameter note in part of the email body

  tasks:
  - name: "Create temporary directory"
    ansible.windows.win_tempfile:
      state: directory
    register: tempdir

  - name: "Scipt Operations"
    block:
    - name: "Copy Scripts to Host"
      ansible.windows.win_copy:
        src: "files/{{var_ps_folder}}"
        dest: "{{ tempdir.path }}"

    - name: check if file exist
      ansible.windows.win_stat:
        path: "{{ tempdir.path }}\\{{var_ps_folder}}\\{{var_ps_script_file}}"
      register: file_data

    - name: Run PowerShell script
      when: file_data.stat.exists == true
      ansible.windows.win_command: powershell.exe -ExecutionPolicy ByPass
        -File "{{ tempdir.path }}\\{{var_ps_folder}}\\{{var_ps_script_file}}"
        -Action "{{var_parameter_action}}" -eMailReport "{{var_eMailReport}}"
        -SMTPServer "{{var_SMTPServer}}"
        -MailToString "{{var_MailToString}}"
        -MailCcString "{{var_MailCcString}}"
        -OUPath "{{var_OUPath}}"
        -MailSubjectstring "{{var_MailSubjectstring}}"
        -DomainName "{{var_DomainName}}"

    - name: "List the debug folder content"
      ansible.windows.win_shell: "ls -Recurse {{ tempdir.path }}\\{{var_ps_folder}}\\debug"

    always:
    - name: "Cleanup Temporary Files"
      ansible.windows.win_file:
        state: absent
        path: "{{ tempdir.path }}"
